apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmcomdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminapp
  template:
    metadata:
      labels:
        app: adminapp
    spec:
      containers:
      - name: my-admin-app
        image: jenie779/servicedemo:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: admin-app-svc
spec:
  selector:
    app: adminapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer